
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - dhcp.routerd.net
  resources:
  - dhcpservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dhcp.routerd.net
  resources:
  - dhcpservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ipam.routerd.net
  resources:
  - ipv4leases
  - ipv6leases
  - ipv4pools
  - ipv6pools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.routerd.net
  resources:
  - ipv4leases/status
  - ipv6leases/status
  - ipv4pools/status
  - ipv6pools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: dhcp-role
rules:
- apiGroups:
  - dhcp.routerd.net
  resources:
  - dhcpservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dhcp.routerd.net
  resources:
  - dhcpservers/status
  verbs:
  - get
- apiGroups:
  - ipam.routerd.net
  resources:
  - ipv4pools
  - ipv6pools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ipam.routerd.net
  resources:
  - ipv4leases
  - ipv6leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.routerd.net
  resources:
  - ipv4leases/status
  - ipv6leases/status
  - ipv4pools/status
  - ipv6pools/status
  verbs:
  - get
  - patch
