apiVersion: dhcp.routerd.net/v1alpha1
kind: DHCPServer
metadata:
  name: sample
spec:
  ipv4:
    pool:
      name: sample
    gateway: 192.168.250.1
    nameServers:
      - 192.168.250.1

  ipv6:
    pool:
      name: sample
    gateway: "fde4:fa92:1362:78a7::1"
    nameServers:
      - "fde4:fa92:1362:78a7::1"

  hostInterfaceName: br1
---
apiVersion: ipam.routerd.net/v1alpha1
kind: IPv4Pool
metadata:
  name: sample
spec:
  cidr: 192.168.250.0/24
  leaseDuration: 1h
---
apiVersion: ipam.routerd.net/v1alpha1
kind: IPv6Pool
metadata:
  name: sample
spec:
  cidr: fde4:fa92:1362:78a7::/64
  leaseDuration: 1h
