apiVersion: ipam.routerd.net/v1alpha1
kind: IPv4Pool
metadata:
  name: sample
spec:
  cidr: 172.20.0.0/24
  leaseDuration: 30s
---
apiVersion: ipam.routerd.net/v1alpha1
kind: IPv6Pool
metadata:
  name: sample
spec:
  cidr: fd9c:fd74:6b8d:1020::/64
  leaseDuration: 30s
