name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - run: go get golang.org/x/tools/cmd/goimports
    - uses: actions/setup-python@v2
    - uses: actions/checkout@v2
    - uses: pre-commit/action@v2.0.0
    - run: make ci-test
